jobconfig:
  presets: []
  presubmits: {}
  postsubmits: {}
  periodics: []
prowconfig:
  tide:
    syncperiodstring: ""
    syncperiod: 0s
    statusupdateperiodstring: ""
    statusupdateperiod: 0s
    queries: []
    mergetype: {}
    targeturl: ""
    prstatusbaseurl: ""
    blockerlabel: ""
    squashlabel: ""
    maxgoroutines: 0
    contextoptions:
      tidecontextpolicy:
        skipunknowncontexts: null
        requiredcontexts: []
        requiredifpresentcontexts: []
        optionalcontexts: []
        frombranchprotection: null
      orgs: {}
  plank:
    controller:
      joburltemplatestring: ""
      joburltemplate: null
      reporttemplatestring: ""
      reporttemplate: null
      maxconcurrency: 0
      maxgoroutines: 0
      allowcancellations: false
    podpendingtimeoutstring: ""
    podpendingtimeout: 0s
    defaultdecorationconfig: null
    joburlprefix: ""
  sinker:
    resyncperiodstring: ""
    resyncperiod: 0s
    maxprowjobagestring: ""
    maxprowjobage: 0s
    maxpodagestring: ""
    maxpodage: 0s
  deck:
    spyglass:
      viewers: {}
      regexcache: {}
      sizelimit: 0
    tideupdateperiodstring: ""
    tideupdateperiod: 0s
    hiddenrepos: []
    externalagentlogs: []
    branding: null
  branchprotection:
    policy:
      protect: null
      requiredstatuschecks: null
      admins: null
      restrictions: null
      requiredpullrequestreviews: null
    protecttested: false
    orgs: {}
    allowdisabledpolicies: false
  orgs: {}
  gerrit:
    tickintervalstring: ""
    tickinterval: 0s
    ratelimit: 0
  jenkinsoperators: []
  prowjobnamespace: ""
  podnamespace: ""
  loglevel: ""
  pushgateway:
    endpoint: ""
    intervalstring: ""
    interval: 0s
  ownersdirblacklist:
    repos: {}
    default: []
  pubsubsubscriptions: {}
