plugins:
  test-org/test-repo:
  - config-updater
  - approve
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - heart
  - override
externalplugins:
  test-org/test-repo: []
owners:
  mdyamlrepos: []
  skipcollaborators: []
  labelsblacklist: []
approve:
- repos:
  - test-org/test-repo
  issuerequired: false
  deprecatedimplicitselfapprove: null
  requireselfapproval: null
  lgtmactsasapprove: true
  deprecatedreviewactsasapprove: null
  ignorereviewstate: false
usedeprecatedselfapprove: false
usedeprecatedreviewapprove: false
blockades: []
blunderbuss:
  reviewercount: null
  maxreviewercount: 0
  fileweightcount: null
  excludeapprovers: false
cat:
  keypath: ""
cherrypickunapproved:
  branchregexp: ""
  branchre: null
  comment: ""
configupdater:
  maps: {}
  configfile: ""
  pluginfile: ""
golint: null
heart:
  adorees: []
  commentregexp: ""
  commentre: null
label: null
lgtm: []
repomilestone: {}
requirematchinglabel: []
requiresig:
  grouplisturl: ""
slack:
  mentionchannels: []
  mergewarnings: []
sigmention:
  regexp: ""
  re: null
size: null
triggers: []
welcome: []
